### ISSUE TITLE
您好，可否提供一下您的语言模型？

### ISSUE THREAD

**Issue by PPPPPYJ** [Sundy1219/eesen-for-thchs30#13]
您好，非常感谢您所做的工作，我直接采用了thchs30附带的语言模型，但是我在测试中发现总是有如下的错误，估计可能是语言模型或者词典不匹配，可否请您提供一下您测试成功的这两个文件？或者您用thchs30自带的语言模型和词典测试一下，告诉我文件所在的具体位置或者所需的修改，谢谢您！再一次感谢您对这项工作的辛勤付出！

Traceback (most recent call last):
  File "utils/prep_ctc_trans.py", line 75, in <module>
    out_line += dict[unk_word] + ' '
KeyError: '<UNK>'
Traceback (most recent call last):
  File "utils/prep_ctc_trans.py", line 75, in <module>
    out_line += dict[unk_word] + ' '
KeyError: '<UNK>'

**Comment by Sundy1219** [comment]
建议你自己准备个建模单元文件units.txt和相应的字典lexicon.txt，
[lexicon.txt](https://github.com/Sundy1219/eesen-for-thchs30/files/2754047/lexicon.txt)
[units.txt](https://github.com/Sundy1219/eesen-for-thchs30/files/2754048/units.txt)
语言模型的生成是单独训练的，但是训练的词是要在这个词典里的，然后根据这个建模单元，lexicon.txt,和lm.gz生成相应的TLG.fst

**Comment by Sundy1219** [comment]
有什么问题，可以问这位小伙伴＠fantasyoooo，你遇到的问题，我都给他解答了．在issues中可以找到的问题

**Comment by liubin3702** [comment]
请问你在这个项目中的问题解决了吗
